### PR TITLE
Blender hack

### PR DESCRIPTION
**Pull request by aoakalin**
Hey, I have found a crazy useful hack. With this small change, your tool is able to support ".blend" file to be imported as a CC3 character.

My progress is as follows:

* Export character from CC3 by choosing Blender preset.
* Import that character into Blender using your Blender plugin.
* File > External Data > Pack Resources, so that materials will be packed to the ".blend" file.
* Delete everything other than ".blend" file.
* Go back to CC3, export the exact same character by choosing Unity preset this time to the same folder with the ".blend" file, and not sure if necessary but give it the exact same name as the previous FBX and ".blend" file.
* Go to Unity, import the FBX file for Unity preset using this plugin, so that proper Unity materials will be generated.
* Delete the FBX file as we don't need it anymore.
* Right click and import the old ".blend" file. Previously generated Unity materials will be used with your ".blend" file, prefab will also use blend file now.

Why I did such a thing? You can do edits on blend file and immediately see the result on Unity. This method helped me tremendously especially when fixing weight paint issues on my model, also helped me with making my inventory system so that my character can easily change clothes. It is like CC3 - Blender - Unity live link with some horrible pre-configuration steps; but definitely worth the pain in my opinion.

I wanted to share my method with you. I hope you can come up with something even more better than this, as you know the in's and out's way better. Making this somehow better should allow a lot more options for people that use CC3/iClone with Unity and Blender. Also, this hack works exactly the same with you URP and HDRP repositories as well, but I'm opening pull request on just this repository as I only downloaded this one.

Here are sample step by step screenshots that show how everything is setup correctly with this method, and whenever you edit on Blender, you instantly see it on Unity without another FBX export import step.

### CODE REVIEW

**Comment by soupday** [comment]
I've been meaning to do an 'export to Unity' function in the Blender add-on for a while, but as an fbx. I had not considered leaving it as a .blend file in the Unity project, but now that you've pointed it out it's a much better idea to keep it as a blend file.

There are a few issues to take care of in that case, mostly to do with Blender changing duplicate names on objects and materials, which means they become disconnected with the .json file, and so won't set up correctly in Unity. But all of that has been solved in the code to round-trip back to CC3, so it's just a matter of piecing it all together for an 'Export to/Save in Unity Project' button.

As this will need to update the .json file with any new object names, this also means that any material parameter changes can also be passed on to Unity too, so you can adjust things like skin settings/hair colours in Blender and Unity will pick up these changes when building the materials.

All that's missing then is the DiffuseAlpha, MetallicAlpha and HDRP mask textures that the Unity shaders need (and aren't in the Blender exports), which need to be constructed from the individual raw textures, but that's easily done with compute shaders.

**Comment by aoakalin** [comment]
I'm really hyped to hear that it is possible on your end. It is essentially the most bothering missing link between Reallusion tools and Unity in my eyes for the past years I had used them together. Yes, I always had the means to do it; but it was always very tedious and time consuming. All of your repositories were such a tremendous improvement over what we had in the past; but this, this is **THE** thing I need most as an Unity developer using Reallusion tools as his main character and animation pipeline. I knew you would have come up with something way more better than me. I'm glad I took the time to do the pull request.

By the way, you can also think about creating the mask textures on Unity side, maybe just after character import button is pressed. Not sure which one might be easier, but just wanted to mention it. This repo has a simple and clean implementation that you can have a look: https://github.com/andydbc/unity-texture-packer

**Comment by soupday** [comment]
Here's the first attempt at the pipeline:
Blender thread: https://forum.reallusion.com/FindPost508564.aspx
Unity thread: https://forum.reallusion.com/FindPost508566.aspx

**Comment by aoakalin** [comment]
Wow, the video looks great! This solves the most painful part of using CC3 together with Unity. Great job man, you really single-handedly solved the usability issues of CC3 and iClone for Unity developers, this is the only thing I wanted and needed, but sadly never had, since the 2 years I had used this pipeline. I had always found a solution to my problems; but it was always frustrating and tedious. At last we have a smooth transition between tools, having Blender as a middle-man offers so much to indie people like me, now I can seriously harness the power of Reallusion workflow.

I had exported 7 different models in near past from CC3 directly to Unity and were using them on a HDRP project. I will export all of them again using this method, and will post my findings on the forum links you shared above.

I'm also closing this pull request as you already provided a better alternative. 👍

**Pull request closed without merging**
